# Generated by Django 2.2.16 on 2022-09-16 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
    ]
