# Generated by Django 2.2.16 on 2022-09-13 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20220912_2114'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-pub_date', 'id'], 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
    ]
