# Generated by Django 2.2.16 on 2022-09-13 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20220913_1836'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-pub_date'], 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-pub_date', 'id'], 'verbose_name': 'Review', 'verbose_name_plural': 'Reviews'},
        ),
    ]
