# Generated by Django 2.2.16 on 2022-09-16 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20220916_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
