# Generated by Django 2.2.16 on 2022-09-13 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20220913_1839'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='titles',
            options={},
        ),
    ]
