# Generated by Django 2.2.16 on 2022-09-16 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20220916_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='field',
        ),
        migrations.AddField(
            model_name='review',
            name='text',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
