# Generated by Django 2.2.16 on 2022-09-13 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_auto_20220913_1947'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Title',
            new_name='Titles',
        ),
    ]
