# Generated by Django 2.2.16 on 2022-09-16 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_auto_20220916_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='id'),
            preserve_default=False,
        ),
    ]
