# Generated by Django 2.2.16 on 2022-09-13 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_auto_20220913_2020'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='titles',
            options={},
        ),
        migrations.RemoveField(
            model_name='titles',
            name='rating',
        ),
    ]
