# Generated by Django 2.2.16 on 2022-09-16 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_auto_20220916_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='field',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(),
        ),
    ]
