# Generated by Django 2.2.16 on 2022-09-16 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0010_auto_20220916_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='field',
        ),
        migrations.RemoveField(
            model_name='review',
            name='text',
        ),
    ]
