# Generated by Django 2.2.16 on 2022-09-13 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0011_auto_20220913_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titles',
            name='genre',
            field=models.ManyToManyField(through='reviews.TitleGenre', to='reviews.Genres', verbose_name='Genre of the creation'),
        ),
    ]
