# Generated by Django 2.2.16 on 2022-09-16 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0011_auto_20220916_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='geeks_field',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
