# Generated by Django 2.2.16 on 2022-09-16 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0012_review_geeks_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='geeks_field',
        ),
        migrations.AddField(
            model_name='review',
            name='text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
