# Generated by Django 2.2.16 on 2022-09-13 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0012_auto_20220913_2032'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='titles',
            options={'ordering': ['name'], 'verbose_name': 'production', 'verbose_name_plural': 'productions'},
        ),
    ]
