# Generated by Django 2.2.16 on 2022-09-13 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0015_auto_20220913_2042'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='titles',
            options={},
        ),
        migrations.RemoveField(
            model_name='titles',
            name='category',
        ),
        migrations.RemoveField(
            model_name='titles',
            name='description',
        ),
        migrations.RemoveField(
            model_name='titles',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='titles',
            name='name',
        ),
        migrations.RemoveField(
            model_name='titles',
            name='year',
        ),
    ]
