# Generated by Django 2.2.16 on 2022-09-13 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0016_auto_20220913_2143'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='titles',
            options={'ordering': ['name'], 'verbose_name': 'production', 'verbose_name_plural': 'productions'},
        ),
        migrations.AddField(
            model_name='titles',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='reviews.Categories', verbose_name='Category of the creation'),
        ),
        migrations.AddField(
            model_name='titles',
            name='description',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Description of the creation'),
        ),
        migrations.AddField(
            model_name='titles',
            name='genre',
            field=models.ManyToManyField(through='reviews.TitleGenre', to='reviews.Genres', verbose_name='Genre of the creation'),
        ),
        migrations.AddField(
            model_name='titles',
            name='name',
            field=models.CharField(default=1, max_length=256, verbose_name='Name of the creation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='titles',
            name='year',
            field=models.IntegerField(default=1, verbose_name='Create year'),
            preserve_default=False,
        ),
    ]
