# Generated by Django 2.2.16 on 2022-09-16 11:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0016_auto_20220916_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)], verbose_name='id'),
        ),
    ]
